
const initTasks = [
  // 완료 (done)
  { id: 1, title: "Elice-일반 인사글 작성", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 2, title: "근로계약서", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 3, title: "엘리스트랙 skim", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 4, title: "1st day checklist", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 5, title: "3주차 검수", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 6, title: "실습코드 업로드 실습", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 7, title: "루프 미팅록 확인", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 8, title: "실습코드 검수사항 반영", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 9, title: "fe 7주차 강의자료 제작", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 10, title: "4주차 테스트 검수", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 11, title: "fe 6주차 자료 검수", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 12, title: "fe 5주차 테스트 검수", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 13, title: "fe 7주차 강의자료 수정", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 14, title: "4주차 테스트 수정 이슈", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 15, title: "fe 5주차 실습 수정 이슈", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 16, title: "AIDT 외주 코드 리뷰 트랜스퍼", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 17, title: "be 5주차 실습 수정 이슈", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 18, title: "fe 5주차 실습 수정 이슈", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 19, title: "6주차 테스트 검수 9/12", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 20, title: "fe 6주차 퀴즈 수정 이슈", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 21, title: "세미나 9/19", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 22, title: "AIDT 리뷰 (1차 15/16)", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 23, title: "fe 7주차 퀴즈 실습 제작", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 24, title: "be 7주차 검수 9/11", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 25, title: "fe 8주차 검수 9/11", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 26, title: "레몬베이스 1:1 셋업", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 27, title: "fe 7주차 테스트 제작", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 28, title: "be 7주차 테스트 검수", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 29, title: "fd 1주차 강의자료 수정 이슈", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 30, title: "1:1 미팅", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 31, title: "fe 8주차 테스트 검수", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 32, title: "fe 1차 프로젝트 제작", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 33, title: "be 8주차 검수", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 34, title: "be 11주차 외주 자료 검수", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 35, title: "fe 2주차 강의 수정 이슈", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 36, title: "24년 4분기 OKR 작성", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 37, title: "fe 2주차 실습 수정 이슈", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 38, title: "fe 3주차 자료 문의", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 39, title: "be 기제작 문법 최신화", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 40, title: "박상수 강사님 be 17 계약", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 41, title: "be 12주차 외주 자료 검수", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 42, title: "fe 3주차 실습 수정 이슈", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 43, title: "be 11주차 테스트 검수", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 44, title: "sparcs 예선 초안 제작", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 45, title: "sparcs 예선 검수", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 46, title: "fe 11주차 테스트 문법 이슈", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 47, title: "fe 12주차 자료 수정 이슈", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 48, title: "be 13주차 외주 자료 검수", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 49, title: "fe 2차 프로젝트 가이드 작성", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 50, title: "be 12주차 테스트 제작", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 51, title: "sparcs 예선 수정", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 52, title: "fe 12주차 강의자료 수정 이슈", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 53, title: "be 14주차 외주 자료 검수", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 54, title: "be 13주차 테스트 검수", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 55, title: "fe 13주차 실습 수정 이슈", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 56, title: "sparcs PM 직군 평가", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 57, title: "fe 13주차 퀴즈 수정 이슈", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 58, title: "2024 4분기 신규 과목 기획", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 59, title: "fe 6주차 실습 수정 이슈", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 60, title: "fe 13주차 자료 수정 이슈", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 61, title: "Sparcs 온디맨드 가이드 작성", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 62, title: "sparcs 온디맨드 테스트", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 63, title: "프론트엔드 프로젝트 자료 제작", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 64, title: "be 14주차 테스트 검수", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 65, title: "sparcs 18일 문의사항", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 66, title: "fe 16주차 강의자료 제작", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 67, title: "fe 16주차 퀴즈실습 제작", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 68, title: "be 15주차 테스트 검수", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 69, title: "인도네시아 커리큘럼 작성", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 70, title: "be 16주차 자료 개정", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 71, title: "fe 16주차 실습 수정 이슈", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 72, title: "fe 16주차 테스트 제작", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 73, title: "React 프로젝트 런박스 세팅", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 74, title: "be 12주차 강의자료 수정 이슈", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 75, title: "be 17주차 외주자료 검수", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 76, title: "웹 개발 과목 전수 조사 + 시장 조사", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 77, title: "be 2주차 실습자료 수정 이슈", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 78, title: "fe 17주차 강의자료 검수", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 79, title: "fe 17주차 퀴즈실습 검수", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 80, title: "fe 17주차 테스트 검수", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 81, title: "be 18주차 외주자료 검수", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 82, title: "be 1주차 실습자료 수정", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 83, title: "3차 프로젝트 가이드 작성", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 84, title: "React 프로젝트 코드 제작", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 85, title: "웹 리뉴얼 커리큘럼 초안", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 100, title: "be 2주차 자료 수정 이슈", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 101, title: "be 16주차 강의자료 수정 이슈", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 102, title: "be 18주차 실습 수정 이슈", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 103, title: "be 3주차 실습문제 수정 이슈", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 104, title: "React 프로젝트 지시사항 작성", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 105, title: "kdt vm 가이드 수정", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 106, title: "kdt 프로젝트 평가기준 작성", link: "", status: 4, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },

  // 검수 (review)
  { id: 107, title: "프론트엔드 커리큘럼 고도화", link: "", status: 3, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 108, title: "fe 17주차 추가실습 검수", link: "", status: 3, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },

  // 진행 (work)
  { id: 87, title: "태스크 트래커 앱 제작", link: "", status: 2, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 109, title: "포폴 트랙 프론트 심사", link: "", status: 2, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 110, title: "Git 과목 커리큘럼 작성", link: "", status: 2, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 111, title: "HTML 프로젝트 커리큘럼 작성", link: "", status: 2, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 112, title: "JS Method 과목 커리큘럼 작성", link: "", status: 2, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 113, title: "be 1차 프로젝트 가이드 작성", link: "", status: 2, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },

  // 계획 (plan)
  { id: 88, title: "프론트엔트 테스트 시장 조사", link: "", status: 1, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 114, title: "kdt let var 수정 ", link: "", status: 1, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },

  // 구상 (idea)
  { id: 89, title: "애니메이션 툴 연구 (도레미파이썬 case study)", link: "", status: 0, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 90, title: "Three.js 연구 기획", link: "", status: 0, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 91, title: "학생 타게팅 수업 연구 (로블록스, 마크 모딩)", link: "", status: 0, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 92, title: "react native 조사", link: "", status: 0, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 93, title: "VS Code 실습 편집 익스텐션 제작", link: "", status: 0, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 94, title: "프론트엔드 테스트 파일럿 문항 제작", link: "", status: 0, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 95, title: "TOPA 응시하기", link: "", status: 0, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 96, title: "AI 교수학습도구 조사", link: "", status: 0, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 97, title: "AI 코드 에디터 사용 과목 연구", link: "", status: 0, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 98, title: "와이어 UI 기반 Nest 서버 제작기?", link: "", status: 0, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
  { id: 99, title: "엘리스 클라우드 튜토리얼 자료 제작", link: "", status: 0, createdAt: new Date(0), startedAt: new Date(0), reviewedAt: new Date(0), completedAt: new Date(0) },
];

const initData = {
  nextId: 115,
  tasks: initTasks,
  sortOptions: [
    { sortType: 'id', isAscending: false },
    { sortType: 'id', isAscending: false },
    { sortType: 'id', isAscending: false },
    { sortType: 'id', isAscending: false },
    { sortType: 'id', isAscending: false },
  ],
};

export const initLocalStorage = () => {
  window.localStorage.setItem('task-tracker-app', JSON.stringify(initData));
};

export const resetLocalStorage = () => {
  window.localStorage.removeItem('task-tracker-app');
};